server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /health {
        return 200 '{"status":"ok"}';
        add_header Content-Type application/json;
    }

    location /api/calc/ {
        proxy_pass http://calc-api:3001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/history/ {
        proxy_pass http://history-api:3002/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
