version: '3.8'

services:
  frontend:
    image: ${DOCKERHUB_USER}/small-frontend:${IMAGE_TAG}
    ports:
      - "80:80"
    restart: always
    depends_on:
      - calc-api
      - history-api

  calc-api:
    image: ${DOCKERHUB_USER}/small-calc-api:${IMAGE_TAG}
    ports:
      - "3001:3001"
    restart: always

  history-api:
    image: ${DOCKERHUB_USER}/small-history-api:${IMAGE_TAG}
    ports:
      - "3002:3002"
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
